name: firebase_auth_line_sign_in
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_line_sdk: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
